package com.howtodoinjava.jaxb.unmarshaller;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;

/**
 * A class without {@code @XmlRootElement}, as generated by xjc for a complex type.
 * It can only be read with {@code unmarshal(source, Track.class)}, which returns a JAXBElement.
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class Track {

  private String title;
  private int seconds;

  public String getTitle() { return title; }
  public int getSeconds() { return seconds; }

  @Override
  public String toString() {
    return "Track[title=" + title + ", seconds=" + seconds + "]";
  }
}
